### ISSUE TITLE
Unplug the network cable when call file trigger dead lock

### ISSUE THREAD

**Issue by lipeng5555** [mz-automation/libiec61850#369] opened 2022-01-06 15:44 UTC
I am a C++ Client App in Windows，When Call many files then Unplug the network cable，call file will timeout in mms_client_connection.c
1、call static void mmsIsoCallback(IsoIndication indication, void* parameter, ByteBuffer* payload)
2、Semaphore_wait(self->outstandingCallsLock);
3、call handleAsyncResponse(self, NULL, 0, &(self->outstandingCalls[i]), MMS_ERROR_SERVICE_TIMEOUT);
4、in else if (outstandingCall->type == MMS_CALL_TYPE_FILE_READ), call handler(outstandingCall->invokeId, outstandingCall->userParameter, err, frsmId, NULL, 0, false);
5、call handler(outstandingCall->invokeId, outstandingCall->userParameter, err, frsmId, NULL, 0, false);
6、call call->invokeId = MmsConnection_fileCloseAsync(self->connection, &mmsError, frsmId, mmsConnectionFileCloseHandler, self);
7、call sendAsyncRequest(self, invokeId, payload, MMS_CALL_TYPE_FILE_CLOSE, handler, parameter, intParam)
8、call addToOutstandingCalls，here will dead lock
When Unplug the network cable，the Connection Error Msg will behind Call File Timeout Msg，So maybe Dead Lock。

**Comment by mzillgith** [comment] 2022-01-10 21:56
This seems to be a duplicate of #285 and is already solved.

**Closed as completed by mzillgith** 2022-01-10 21:56 UTC
